#! /usr/bin/env python3

import sys

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def pairplot(df):
    sns.pairplot(df)
    plt.show()


df = pd.read_csv(sys.stdin)
pairplot(df)
